# -*- coding: utf-8 -*-
"""期中專案.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nXIabu4xay9lGrskyoFLXe_f5hIDLpaC
"""

print("現在要進行楊芷盈 Q＆A 大考驗")
count = 0 #計算進行的次數，設定count = 0，使之能夠開始
while count < 2: ##設定count = 2，使之最多只能玩兩次
  question1 = input("1、楊芷瑩最喜歡的寶可夢？A.夢幻  B.皮卡丘  C.胖丁")
  print(question1)
  if question1 == 'A':
        anwser1 = 10
  elif question1 == 'B':
        anwser1 = 0
  elif question1 == 'C':
        anwser1 = 0
  else:
    anwser1 = 0
    print("嗯⧸⎩⎠⎞͏(・∀・)⎛͏⎝⎭⧹—請好好回答啦！")

  question2 = input('''2、如果進行楊芷盈的母校巡禮，該怎麼坐捷運為最快車程(從新北投出發)？A.紅線轉綠線 B.綠線轉紅線 C.紅線 D.騎摩托車 E.搭計程車''')
  if question2 == 'A':
        anwser2 = 0
  elif question2 == 'B':
        anwser2 = 0
  elif question2 == 'C':
        anwser2 = 10
  elif question2 == 'D':
        anwser2 = 0
  elif question2 == 'E':
        anwser2 = 0
  else:
    anwser2 = 0
    print("嗯⧸⎩⎠⎞͏(・∀・)⎛͏⎝⎭⧹—請好好回答啦！")

  question3 = input('''3、楊芷盈曾經出過車禍導致哪個部位受損? A. 大腦 B.手指 C.左臂 D.心情 E.眉毛''')
  if question3 == 'A':
        anwser3 = 0
  elif question3 == 'B':
        anwser3 = 10
  elif question3 == 'C':
        anwser3 = 0
  elif question3 == 'D':
        anwser3 = 0
  elif question3 == 'E':
        anwser3 = 0
  else:
    anwser3 = 0
    print("嗯⧸⎩⎠⎞͏(・∀・)⎛͏⎝⎭⧹—請好好回答啦！")


  question4 = input("4、楊芷盈最喜歡打桌球了。關於楊芷盈的球皮組合是? A.正手短顆反手短顆 B.正手平面反手平面 C.正手平面反手短顆 D.正手短顆反手平面")
  if question4 == 'A':
        anwser4 = 0
  elif question4 == 'B':
        anwser4 = 0
  elif question4 == 'C':
        anwser4 = 0
  elif question4 == 'D':
        anwser4 = 10
  else:
    anwser4 = 0
    print("嗯⧸⎩⎠⎞͏(・∀・)⎛͏⎝⎭⧹—請好好回答啦！")

  question5 = input('''5、楊芷盈的求職路豐富多端，請問楊芷盈的職涯順序為? A.國稅局-全職桌球教練-資誠會計事務所-勤業眾信會計事務所  B.安永會計事務所-安侯建業會計事務所-資誠會計事務所-勤業眾信會計事務所 C.國稅局-資誠會計事務所-安永會計事務所 D.國稅局-資誠會計事務所-安永會計事務所-待業''')
  if question5 == 'A':
        anwser5 = 0
  elif question5 == 'B':
        anwser5 = 0
  elif question5 == 'C':
        anwser5 = 10
  elif question5 == 'D':
        anwser5 = 0
  else:
    anwser5 = 0
    print("嗯⧸⎩⎠⎞͏(・∀・)⎛͏⎝⎭⧹—請好好回答啦！")

  question6 = input('''6、當楊芷盈對你很不爽時，你應該怎麼做？ A.和她硬碰硬，順便罵她髒話 B.封鎖她 C.想辦法用柔性方式對她，因為她吃軟不吃硬 ''')
  if question6 == 'A':
        anwser6 = 0
  elif question6 == 'B':
        anwser6 = 0
  elif question6 == 'C':
        anwser6 = 10
  else:
    anwser6 = 0
    print("嗯⧸⎩⎠⎞͏(・∀・)⎛͏⎝⎭⧹—請好好回答啦！")

  question7 = input('''7、楊芷盈的女神組合？ A.少女時代潔西卡+詹雯婷+陳羿寧  B.少女時代潔西卡+少女時代潔西卡太妍+陳羿寧 C.林志玲+詹雯婷+陳羿寧''')
  if question7 == 'A':
        anwser7 = 10
  elif question7 == 'B':
        anwser7 = 0
  elif question7 == 'C':
        anwser7 = 0
  else:
    anwser7 = 0
    print("嗯⧸⎩⎠⎞͏(・∀・)⎛͏⎝⎭⧹—請好好回答啦！")

  question8 = input('''8、楊芷盈得到全國桌球大專盃雙打冠軍是哪一年？  A.她的前世  B.2050(預知)  C.2021  D.從未得過 E.2018   F.2020  G.2019''')
  if question8 == 'A':
        anwser8 = 0
  elif question8 == 'B':
        anwser8 = 0
  elif question8 == 'C':
        anwser8 = 0
  elif question8 == 'D':
        anwser8 = 0
  elif question8 == 'E':
        anwser8 = 0
  elif question8 == 'F':
        anwser8 = 0
  elif question8 == 'G':
        anwser8 = 10
  else:
    anwser8 = 0
    print("嗯⧸⎩⎠⎞͏(・∀・)⎛͏⎝⎭⧹—請好好回答啦！")

  question9 = input('''9、如果有四碗食物，楊芷盈吃了最開心是哪一碗？  A.加了香菜的大腸麵線  B.去蔥的豆皮烏龍麵   C.永康街的半筋半肉牛肉麵 D. 溫州大餛飩的鮮蝦餛飩麵  E.羊肉炒麵''')
  if question9 == 'A':
        anwser9 = 0
  elif question9 == 'B':
        anwser9 = 0
  elif question9 == 'C':
        anwser9 = 0
  elif question9 == 'D':
        anwser9 = 10
  elif question9 == 'E':
        anwser9 = 0
  else:
    anwser9 = 0
    print("嗯⧸⎩⎠⎞͏(・∀・)⎛͏⎝⎭⧹—請好好回答啦！")

  question10 =input('''10、楊芷盈真的是一個很棒的人，請問她的優點有?  A.長的可愛  B.努力  C.不輕易放棄  D.孝順 E.對人真誠(總括來看)   F.以上皆是''')

  if question10 == 'A':
        anwser10 = 0
  elif question10 == 'B':
        anwser10 = 0
  elif question10 == 'C':
        anwser10 = 0
  elif question10 == 'D':
        anwser10 = 0
  elif question10 == 'E':
        anwser10 = 0
  elif question10 == 'F':
        anwser10 = 10
  else:
    anwser10 = 0
    print("嗯⧸⎩⎠⎞͏(・∀・)⎛͏⎝⎭⧹—請好好回答啦！")

  score = anwser1+anwser2+anwser3+anwser4+anwser5+anwser6+anwser7+anwser8+anwser9+anwser10

  print("你在楊芷盈 Q＆A 大考驗的分數是"+str(score)+"分")

  if score >= 90:
        print("恭喜你!!!!請截圖並在3/21之後和楊芷盈兌換BFF戒指一枚。")
  elif score >= 80:
        print("恭喜你!!!!請截圖並在3/21之後和楊芷盈兌換她的親筆簽名照兩張。")
  elif score >= 70:
        print("恭喜你!!!!請截圖並在3/21之後和楊芷盈兌換她的親筆簽名照一張。。")
  elif score >= 50:
        print("謝謝你的參與!請截圖並在3/21之後和楊芷盈兌換袖珍面紙一包。")
  elif score >= 30:
        print("再接再厲!!!!請截圖並在3/21之後和楊芷盈兌換此份考卷的詳解")
  elif score <= 20:
        print("加油，別放棄!!!請截圖並在3/21之後和楊芷盈兌換「你不可不知的楊芷盈」線上課一堂")
  else:
        print("你真的是楊芷盈的朋友嗎?")

  count += 1 #每經過一輪count會+1
  if count == 1:
        while True:
            Please = input("請問還需要再測試一次嗎（Y/N）")
            if Please.lower()== "y":
                print("N恭喜你再次獲得一次機會")
                count < 2 # 設定為小於2，使之 break 出內部迴圈，重問一次問題
                break
            elif Please.lower()== "n":
                count = 2  # 設定為等於2，使之 break 出外部迴圈，直接結束
                break
            else:
                print("請輸入有效的選項")

print("請對她保密這個測驗，感謝你(´▽`ʃ♡ƪ)") #最後結束必會印出的

